language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer require --dev cerbero/workflow:2.*

script:
  - php vendor/bin/phpspec run
  - php vendor/bin/codecept run